# Generated by Django 2.1.3 on 2019-01-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(max_length=20)),
                ('hacker_id', models.IntegerField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submission', models.IntegerField(max_length=20)),
                ('total_accepect_submissions', models.IntegerField(max_length=20)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Challenges')),
            ],
        ),
        migrations.CreateModel(
            name='View_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(max_length=20)),
                ('total_unique_views', models.IntegerField(max_length=20)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Challenges')),
            ],
        ),
        migrations.AddField(
            model_name='colleges',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='challenges',
            name='college_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Colleges'),
        ),
    ]
